# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jJeFgFObzSvwEuqHfTpjjiEOGsoGaRI
"""



words = input("Введите строку с несколькими словами: ").split

new_words = []
for word in words:
    transformed = ""
    # Цикл по буквам
    for i, letter in enumerate(word):
        transformed += letter.upper()
        if i != len(word) - 1:
            transformed += " "
    new_words.append(transformed)

# Количество слов в исходной строке
word_count = len(words)

char_count = 0
for item in new_words:
    char_count += len(item)
joined_string = "|".join(new_words)

# Создание кортежа
result_tuple = (words, new_words, word_count, char_count)

# Вывод типов и значений
print("Тип переменной words:", type(words))
print("Тип переменной new_words:", type(new_words))
print("Тип переменной word_count:", type(word_count))
print("Тип переменной char_count:", type(char_count))
print("Тип переменной joined_string:", type(joined_string))
print("Тип переменной result_tuple:", type(result_tuple))

print("\nСписок исходных слов:", words)
print("Новый список слов:", new_words)
print("Объединённая строка:", joined_string)
print("Кортеж:", result_tuple)

# 7. Проверка условия
check = char_count > 20
print("\nПроверка (количество символов > 20):", check)